- 외래키 삭제 명령어
alert table '테이블 명' drop foreign '제약 키 명';
alter table menu_tb drop foreign key FK_MENU_TB_TO_MENU_TB;


- 제약 키 명 확인
show create table board_category_tb;
show create table board_comment_tb;
show create table board_image_tb;
show create table board_tb;
show create table code_tb;
show create table ionicboard_tb;
show create table like_tb;
show create table location_tb;
show create table main_tb;
show create table menu_tb;
show create table notice_tb;
show create table record_comment_tb;
show create table record_cover_tb;
show create table record_picture_tb;
show create table record_schedule_tb;
show create table record_tb;
show create table together_detail_tb;
show create table together_tb;
show create table train_tb;
show create table user_photo_tb
show create table user_tb;

- 테이블 생성 정보
CREATE TABLE `board_comment_tb` (
  `COMMENT_NO` int(11) NOT NULL AUTO_INCREMENT,
  `TARGET_COMMENT_NO` int(11) DEFAULT NULL COMMENT 'NULL이면 최상위',
  `BOARD_NO` int(11) NOT NULL,
  `USER_UID` varchar(100) NOT NULL,
  `CONTENT` varchar(1000) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`COMMENT_NO`),
  KEY `FK_BOARD_TB_TO_BOARD_COMMENT_TB` (`BOARD_NO`),
  KEY `FK_USER_TB_TO_BOARD_COMMENT_TB` (`USER_UID`),
  KEY `FK_BOARD_COMMENT_TB_TO_BOARD_COMMENT_TB` (`TARGET_COMMENT_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `board_image_tb` (
  `IMAGE_NO` int(11) NOT NULL AUTO_INCREMENT,
  `BOARD_NO` int(11) NOT NULL,
  `PATH` varchar(200) NOT NULL,
  `SIZE` int(11) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`IMAGE_NO`),
  KEY `FK_BOARD_TB_TO_BOARD_IMAGE_TB` (`BOARD_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `board_tb` (
  `BOARD_NO` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_NO` int(11) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `USER_UID` varchar(100) NOT NULL,
  `CONTENT` varchar(1000) NOT NULL COMMENT '이미지 추가는 url받아서 태그형식으로',
  `VIEW_CNT` int(11) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`BOARD_NO`),
  KEY `FK_USER_TB_TO_BOARD_TB` (`USER_UID`),
  KEY `FK_BOARD_CATEGORY_TB_TO_BOARD_TB` (`CATEGORY_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8


CREATE TABLE `code_tb` (
  `FILE_NO` int(11) NOT NULL AUTO_INCREMENT,
  `RECORD_NO` int(11) DEFAULT NULL,
  `SCHEDULE_NO` int(11) DEFAULT NULL,
  PRIMARY KEY (`FILE_NO`),
  KEY `FK_RECORD_SCHEDULE_TB_TO_CODE_TB` (`SCHEDULE_NO`),
  KEY `FK_RECORD_TB_TO_CODE_TB` (`RECORD_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `ionicboard` (
  `no` int(11) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `writer` varchar(30) DEFAULT NULL,
  `content` varchar(3000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `like_tb` (
  `LIKE_NO` int(11) NOT NULL AUTO_INCREMENT,
  `TARGET_NO` int(11) NOT NULL,
  `TARGET_TYPE` int(11) NOT NULL COMMENT '1:게시글, 2:댓글',
  `USER_UID` varchar(100) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LIKE_NO`),
  KEY `FK_USER_TB_TO_LIKE_TB` (`USER_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `location_tb` (
  `LOCATION_NO` int(11) NOT NULL,
  `NAME` varchar(50) NOT NULL COMMENT '1.서울, 2.경기, ..., 11.제주도, ...',
  PRIMARY KEY (`LOCATION_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8



CREATE TABLE `main_tb` (
  `MAIN_NO` int(11) NOT NULL AUTO_INCREMENT,
  `USER_UID` varchar(100) DEFAULT NULL,
  `CONTENT` varchar(1000) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`MAIN_NO`),
  KEY `FK_USER_TB_TO_MAIN_TB` (`USER_UID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8



CREATE TABLE `menu_tb` (
  `MENU_NO` int(11) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `URL` varchar(255) DEFAULT NULL,
  `PARENT_MENU_NO` int(11) DEFAULT NULL,
  `LEVEL` int(11) DEFAULT NULL,
  `TYPE` enum('C','W') NOT NULL COMMENT '공통은 ''C'' 웹만 있는 메뉴는 ''W''',
  PRIMARY KEY (`MENU_NO`),
  KEY `FK_MENU_TB_TO_MENU_TB` (`PARENT_MENU_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `notice_tb` (
  `NOTICE_NO` int(11) NOT NULL AUTO_INCREMENT,
  `USER_UID` varchar(100) NOT NULL,
  `TYPE` varchar(10) NOT NULL,
  `BOARD_NO` int(11) NOT NULL,
  `URL` varchar(255) NOT NULL,
  `CHECK` enum('Y','N') NOT NULL,
  `READ_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`NOTICE_NO`),
  KEY `FK_USER_TB_TO_NOTICE_TB` (`USER_UID`),
  KEY `FK_BOARD_TB_TO_NOTICE_TB` (`BOARD_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `record_comment_tb` (
  `COMMENT_NO` int(11) NOT NULL AUTO_INCREMENT,
  `SCHEDULE_NO` int(11) NOT NULL,
  `USER_UID` varchar(100) NOT NULL,
  `CONTENT` varchar(1000) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`COMMENT_NO`),
  KEY `FK_RECORD_SCHEDULE_TB_TO_RECORD_COMMENT_TB` (`SCHEDULE_NO`),
  KEY `FK_USER_TB_TO_RECORD_COMMENT_TB` (`USER_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `record_cover_tb` (
  `COVER_NO` int(11) NOT NULL AUTO_INCREMENT,
  `RECORD_NO` int(11) DEFAULT NULL,
  `REAL_PATH` varchar(200) DEFAULT NULL,
  `FILE_PATH` varchar(5000) DEFAULT NULL,
  `ORI_NAME` varchar(200) DEFAULT NULL,
  `FILE_NAME` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`COVER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `record_picture_tb` (
  `BACKGROUND_NO` int(11) NOT NULL AUTO_INCREMENT,
  `REALPATH` varchar(200) NOT NULL,
  `FILEPATH` varchar(200) NOT NULL,
  `ORINAME` varchar(200) NOT NULL,
  `FILENAME` varchar(200) NOT NULL,
  `FILE_NO` int(11) DEFAULT NULL,
  PRIMARY KEY (`BACKGROUND_NO`),
  KEY `FK_CODE_TB_TO_RECORD_PICTURE_TB` (`FILE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `record_schedule_tb` (
  `SCHEDULE_NO` int(11) NOT NULL AUTO_INCREMENT,
  `RECORD_NO` int(11) NOT NULL,
  `TYPE` varchar(10) NOT NULL,
  `PRICE` int(11) DEFAULT NULL,
  `DEPARTURE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DATE` int(11) NOT NULL,
  `CONTENT` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`SCHEDULE_NO`),
  KEY `FK_RECORD_TB_TO_RECORD_SCHEDULE_TB` (`RECORD_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `record_tb` (
  `RECORD_NO` int(11) NOT NULL AUTO_INCREMENT,
  `USER_UID` varchar(100) NOT NULL,
  `DEPARTURE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ARRIVE_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TITLE` varchar(200) NOT NULL,
  `BUDGET` int(11) DEFAULT NULL,
  `PICTURE` int(11) DEFAULT NULL,
  `PERIOD` varchar(100) DEFAULT NULL,
  `BACKGROUND_NO` int(11) DEFAULT '0',
  `FILE_NO` int(11) DEFAULT '0',
  PRIMARY KEY (`RECORD_NO`),
  KEY `FK_USER_TB_TO_RECORD_TB` (`USER_UID`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8


CREATE TABLE `together_detail_tb` (
  `TOGETHER_DETAIL_NO` int(11) NOT NULL AUTO_INCREMENT,
  `TOGETHER_NO` int(11) DEFAULT NULL,
  `CONTENT` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`TOGETHER_DETAIL_NO`),
  KEY `FK_TOGETHER_TB_TO_TOGETHER_DETAIL_TB` (`TOGETHER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=437 DEFAULT CHARSET=utf8


CREATE TABLE `together_tb` (
  `TOGETHER_NO` int(11) NOT NULL AUTO_INCREMENT,
  `URL` varchar(255) NOT NULL,
  `TITLE1` varchar(200) DEFAULT NULL,
  `TITLE2` varchar(200) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`TOGETHER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1645 DEFAULT CHARSET=utf8


CREATE TABLE `train_tb` (
  `STATION_NO` int(11) NOT NULL AUTO_INCREMENT,
  `STATION_TITLE` varchar(100) NOT NULL,
  `STATION_VITAL` int(11) DEFAULT '0',
  PRIMARY KEY (`STATION_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=367 DEFAULT CHARSET=utf8


CREATE TABLE `user_photo_tb` (
  `PHOTO_NO` int(11) NOT NULL AUTO_INCREMENT,
  `USER_UID` varchar(100) NOT NULL,
  `TYPE` int(11) NOT NULL COMMENT '1:프로필, 2:배경',
  `PATH` varchar(200) NOT NULL,
  `SIZE` int(11) NOT NULL,
  `REG_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PHOTO_NO`),
  KEY `FK_USER_TB_TO_USER_PHOTO_TB` (`USER_UID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8


CREATE TABLE `user_tb` (
  `USER_UID` varchar(100) NOT NULL,
  `DISPLAY_NAME` varchar(100) NOT NULL,
  `PHOTO_URL` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(40) DEFAULT NULL,
  `PROVIDER_UID` varchar(100) DEFAULT NULL,
  `PROVIDER_NAME` varchar(100) DEFAULT NULL,
  `PROVIDER_DISPLAY_NAME` varchar(100) DEFAULT NULL,
  `PROVIDER_PHOTO_URL` varchar(255) DEFAULT NULL COMMENT '1.처음 계정 인증시 photo_url이 있으면 넣고 없으면 default사진 2.이후 이미지 변경 시 이미지 업로드 하고, user_photo에 등록하고 업데이트',
  `PROVIDER_EMAIL` varchar(40) DEFAULT NULL,
  `BGPHOTO_URL` varchar(255) DEFAULT NULL,
  `LOCATION_NO` int(11) DEFAULT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `WEBSITE_URL` varchar(255) DEFAULT NULL,
  `INTRODUCE` varchar(1000) DEFAULT NULL,
  `BIRTHDAY` timestamp NULL DEFAULT NULL,
  `REG_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`USER_UID`),
  KEY `FK_LOCATION_TB_TO_USER_TB` (`LOCATION_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8










